spring.datasource.url=jdbc:postgresql://hr-worker-pg16:5432/hr-worker
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=none
